<?php
       
/*
 * Implementation of hook_form_alter()
 */
function custom_filter_form_alter(&$form, &$form_state, $form_id){
  if($form_id == "views_exposed_form"){
  	$form['tid']['#options']['All'] = t(' ');
    $form['tid']['#options'][29] = t(' ');
    $form['tid']['#options'][33] = t(' ');
    $form['tid']['#options'][31] = t(' ');
    $form['tid']['#options'][32] = t(' ');
    $form['tid']['#options'][30] = t(' ');
    

  }
}